org.gradle.jvmargs=-Xmx1536m -XX:+UseSerialGC
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.caching=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx768m -XX:+UseSerialGC
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
